directories: 
  - "/workspace/ywh_data/DataProcessNew/pexels1k/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/pexels_hengping/videos_multi_step1"
  
remove_last_flag: True
multi_person: True
keypoint_suffix_name: "_keypoints"
bbox_suffix_name: "_bboxes"
target_video_suffix_name: "_filtered"
target_pose_video_suffix_name: "_filtered_dwpose"
target_keypoint_suffix_name: "_filtered_keypoints"
target_ref_image_suffix_name: "_ref_image"
draw_pose: True

