directories: 
  - "/workspace/ywh_data/DataProcessNew/bilibili_dance_shuping_0929/videos_step1"
  - "/workspace/ywh_data/DataProcessNew/bili_shuping_0929/videos_step1"

  
remove_last_flag: True
multi_person: False
keypoint_suffix_name: "_keypoints"
bbox_suffix_name: "_bboxes"
target_video_suffix_name: "_filtered"
target_pose_video_suffix_name: "_filtered_dwpose"
target_keypoint_suffix_name: "_filtered_keypoints"
target_ref_image_suffix_name: "_ref_image"
draw_pose: True
