directories: 
  - "/workspace/ywh_data/DataProcess/bili_shuping_0929/videos_filtered"
  # - "/workspace/ywh_data/DataProcess/biaobei_CN_JP_KR/videos"
  # - "/workspace/ywh_data/DataProcess/hd_movie_video_data/videos"
  # - "/workspace/ywh_data/DataProcess/supplier/videos"
  # - "/workspace/ywh_data/DataProcess/bilibili_dance_shuping_0929/videos"
  # - "/workspace/ywh_data/DataProcess/panda70m/videos"
  # - "/workspace/ywh_data/DataProcess/bili_shuping_0929/videos"


  
remove_last_flag: True
reshape_flag: False
points_only_flag: False
pose_type: "dwpose+3dpose"