directories: 
  - "/workspace/ywh_data/DataProcessNew/bili_shuping_0929/videos_step1_filtered"

threed_kpt_dirs:
  - "/workspace/ys_data/filtered_data_phmr/single-person/bili_shuping_0929"
  
reshape_scale: 0
points_only_flag: False
show_feet_flag: False
pose_type: "3dpose"
target_representation_suffix: "_3dpose_test"
remove_last_flag: True
keypoints_suffix_dwpose: "_keypoints"