# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/001/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/002/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/003/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/004/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/005/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/006/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/007/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/008/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/009/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/010/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/011/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/012/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/013/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/014/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/015/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/016/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/017/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/018/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/019/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/020/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/021/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/022/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/023/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/024/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/025/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/026/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/027/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/028/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/029/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/030/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/031/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/032/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/033/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/034/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/035/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/036/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/037/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/038/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/039/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/040/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/041/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/042/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/043/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/044/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/045/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/046/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/047/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/048/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/049/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/050/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/051/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/052/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/053/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/054/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/055/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/056/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/057/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/058/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/059/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/060/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/061/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/062/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/063/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/064/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/065/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/066/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/067/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/068/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/069/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/070/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/071/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/072/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/073/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/074/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/075/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/076/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/077/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/078/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/079/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/080/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/081/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/082/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/083/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/084/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/085/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/086/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/087/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/088/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/089/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/090/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/091/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/092/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/093/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/094/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/095/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/096/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/097/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/098/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/099/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/100/ref_image_video"


videos_per_worker: 100    # 多少个一组
num_workers_per_proc: 1  # 并发数量 >20无明显收益  # 对于pexels等数据集，里面会有一些视频特别长，调大了可能会爆
remove_last: False
single_gpu_test: True  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: False
  save_mp4: False
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"