# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/001/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/002/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/003/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/004/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/005/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/006/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/007/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/008/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/009/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/010/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/011/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/012/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/013/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/014/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/015/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/016/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/017/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/018/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/019/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/020/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/021/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/022/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/023/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/024/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/025/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/026/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/027/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/028/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/029/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/030/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/031/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/032/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/033/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/034/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/035/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/036/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/037/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/038/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/039/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/040/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/041/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/042/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/043/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/044/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/045/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/046/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/047/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/048/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/049/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/050/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/051/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/052/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/053/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/054/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/055/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/056/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/057/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/058/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/059/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/060/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/061/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/062/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/063/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/064/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/065/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/066/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/067/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/068/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/069/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/070/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/071/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/072/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/073/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/074/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/075/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/076/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/077/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/078/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/079/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/080/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/081/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/082/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/083/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/084/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/085/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/086/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/087/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/088/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/089/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/090/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/091/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/092/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/093/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/094/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/095/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/096/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/097/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/098/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/099/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/100/videos"


videos_per_worker: 100    # 多少个一组
num_workers_per_proc: 1  # 并发数量 >20无明显收益  # 对于pexels等数据集，里面会有一些视频特别长，调大了可能会爆
remove_last: False
single_gpu_test: True  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: False
  save_mp4: True
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"