video_roots:
  - "/workspace/ywh_data/DataProcessNew/pexels1k/videos_multi_step1"

videos_per_worker: 100
num_workers_per_proc: 1
remove_last: True
single_gpu_test: True

filter_args:
  use_filter: True
  save_mp4: True
  multi_person: True

name_args:
  keypoint_suffix_name: "_keypoints_test"
  bbox_suffix_name: "_bboxes_test"
  mp4_suffix_name: "_dwpose_test"