# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/DataProcessNew/motionarray_nowat/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/motionarray_nowat_2/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/motionarray_nowat_3/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/high_qual_shuping_1219/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/sft_1w_jingpin_250530/videos_multi_step1"


num_workers_per_proc: 8
remove_last: True
single_gpu_test: False  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: True
  save_mp4: False
  multi_person: True

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"