video_roots:
  - "/workspace/ywh_data/DataProcessNew/pexels1k/videos_step1"

videos_per_worker: 1
num_workers_per_proc: 4
remove_last: False
single_gpu_test: True

filter_args:
  use_filter: False
  save_mp4: True
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints_test"
  bbox_suffix_name: "_bboxes_test"
  mp4_suffix_name: "_dwpose_test"