# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/DataProcessNew/hd_movie_video_data/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/jilupian_dongman_videos/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/biaobei_CN_JP_KR/videos_multi_step1"
  - "/workspace/ywh_data/DataProcessNew/panda70m/videos_multi_step1"
  


videos_per_worker: 12    # 多少个一组
num_workers_per_proc: 8  # 并发数量 >20无明显收益  # 对于pexels等数据集，里面会有一些视频特别长，调大了可能会爆
remove_last: True
single_gpu_test: False  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: True
  save_mp4: False
  multi_person: True

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"