video_roots:
  - "./test_data/test_video_dir"

infer_batch_size: 1
videos_per_worker: 4
num_workers_per_proc: 1
remove_last: False
single_gpu_test: True

filter_args:
  use_filter: False
  save_mp4: True
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"