# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/DataProcessNew/supplier/videos_step1"
  - "/workspace/ywh_data/DataProcessNew/dongman/videos_step1"


videos_per_worker: 10    # 多少个一组
num_workers_per_proc: 16  # 并发数量 >20无明显收益  # 对于pexels等数据集，里面会有一些视频特别长，调大了可能会爆
remove_last: True
single_gpu_test: False  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: True
  save_mp4: False
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"