# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy1/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy1/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy2/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy2/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy3/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy3/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy4/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy4/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy5/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy5/videos"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy6/ref_image_video"
  - "/workspace/ywh_data/crossEval/cross_pair_eval100/toy6/videos"


num_workers_per_proc: 1  # 并发数量 >20无明显收益  # 对于pexels等数据集，里面会有一些视频特别长，调大了可能会爆
remove_last: False
single_gpu_test: True  # 根据save_mp4决定要不要删视频

filter_args:
  use_filter: False
  save_mp4: True
  multi_person: False

name_args:
  keypoint_suffix_name: "_keypoints"
  bbox_suffix_name: "_bboxes"
  mp4_suffix_name: "_dwpose"