# 处理进度见/workspace/ywh_data/DataProcess/ProcessDataViaAPI/process_config.yaml
video_roots:
  - "/workspace/ywh_data/DataProcessNew/pexels1k/videos_step1"

infer_batch_size: 1
videos_per_worker: 4
num_workers_per_proc: 1
remove_last: False
single_gpu_test: True

filter_args:
  use_filter: False
  save_mp4_refine: False

